# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
dependencies:
    override:
        - sudo pip install awscli
jobs:
  build:
    docker:
      - image: devtanc/circleci-node:chakrecore-awscli

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test
      - run: yarn build
      - run:
          name: Deploy build folder to S3
          command: ~/.local/bin/aws s3 sync build s3://schedule.devtanc.com/ --delete --exclude "index.html"
      - run:
          name: Copy index.html and add metadata for cache control
          command: ~/.local/bin/aws s3 cp build/index.html s3://schedule.devtanc.com/index.html --cache-control=no-cache
